[package]
name = "actix-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "actix-server"
path = "main.rs"

[dependencies]
actix-web = "4.4"
actix-rt = "2.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

